using ProductCatalogAPI.Models;

namespace ProductCatalogAPI.Data.Seed
{
    public class DataSeeder
    {
        // Data generated by AI for testing purposes only
        public static void Seed(AppDbContext context)
        {
            // Only seed if tables are empty
            if (context.Categories.Any() || context.Products.Any()) return;

            var categories = new List<Category>
            {
                new() { Name = "Electronics", Description = "Devices and gadgets", CreatedAt = DateTime.UtcNow},
                new() { Name = "Peripherals", Description = "Keyboards and monitors", CreatedAt = DateTime.UtcNow},
                new() { Name = "Accessories", Description = "Cables, cases and adapters", CreatedAt = DateTime.UtcNow}
            };
            context.Categories.AddRange(categories);
            context.SaveChanges();

            var products = new List<Product>
            {
            new()
            {
                Name        = "Laptop Pro 15",
                Description = "High-performance laptop with 16GB RAM",
                Price       = 1299.99m,
                Stock       = 25,
                SKU         = "LP-PRO-15-001",
                IsActive    = true,
                CategoryId  = categories[0].Id
            },
            new()
            {
                Name        = "Wireless Mouse",
                Description = "Ergonomic wireless mouse with long battery life",
                Price       = 39.99m,
                Stock       = 100,
                SKU         = "MS-WL-ERG-001",
                IsActive    = true,
                CategoryId  = categories[1].Id
            },
            new()
            {
                Name        = "Mechanical Keyboard",
                Description = "TKL layout, Cherry MX Red switches",
                Price       = 89.99m,
                Stock       = 50,
                SKU         = "KB-MX-TKL-001",
                IsActive    = true,
                CategoryId  = categories[1].Id
            },
            new()
            {
                Name        = "USB-C Hub",
                Description = "7-in-1 USB-C hub with HDMI and SD card reader",
                Price       = 49.99m,
                Stock       = 75,
                SKU         = "HB-USBC-7IN1-001",
                IsActive    = true,
                CategoryId  = categories[2].Id
            },
            new()
            {
                Name        = "4K Monitor",
                Description = "27-inch 4K IPS display with HDR support",
                Price       = 499.99m,
                Stock       = 15,
                SKU         = "MN-4K-27-001",
                IsActive    = true,
                CategoryId  = categories[0].Id
            },
        };

            context.Products.AddRange(products);
            context.SaveChanges();
        }
    }
}
